version: "3.8"
services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - ${POSTGRES_PORT_PROD:-5432}:5432
    networks:
      - jam-circle-network

  be:
    restart: always
    build: .
    container_name: be
    env_file:
      - .env
    ports:
      - ${FASTAPI_PORT_PROD:-8000}:8000
    networks:
      - jam-circle-network
    depends_on:
      - postgres

networks:
  jam-circle-network:
    driver: bridge
